export const DataAtlas = [
  {
    id: 'slp',
    sede: 'San Luis Potosí',
    description: `Se encuentra ubicado accesando a la ciudad sobre carretera 57 (Av. Benito Juárez) provienentes de las ciudades de México, Querétaro, San Luis Potosí en el corazón de la zona industrial.<br/><br/>Entorno a parques industriales y tecnológicos. Ejemplo: Planta GM a aprox 25/30 minutos. Planta BMW a 30/35 minutos.<br/><br/>Servicio a habitación (Room Service) con menú a la carta en horario de lunes a sábado de 2:00pm a 11:00pm y domingos de 2:00pm a 9:00pm. Otorgado por el hotel Ramada Encore.<br/><br/>En el interior del estacionamiento se encuentra una sucursal Starbucks además del restaurante The Hub del hotel Encore a un costado.`,
    url: 'https://www.wyndhamhotels.com/es-xl/microtel/san-luis-potosi-mexico/microtel-inn-and-suites-by-wyndham-san-luis-potosi/rooms-rates',
    whatsapp: '+5214446174751',
    street: 'Av. Benito Juárez 1600',
    neighborhood: 'Zona Industrial',
    cp: '78395',
    city: 'San Luis Potosí',
    state: 'San Luis Potosí',
    country: 'México',
    rate: 4.6,
    stars: '★★★★',
    ratings: 163,
    mapUrl: 'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d4817.780648240405!2d-100.8981422!3d22.1122771!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x842aa381f6100001%3A0x60c10430967dd9a9!2sMicrotel%20Inn%20%26%20Suites%20by%20Wyndham%20S.L.P.!5e1!3m2!1ses!2sus!4v1748973090994!5m2!1ses!2sus',
    mapDescription: 'Hotel práctico ubicado en la zona industrial de San Luis Potosí, ideal para viajeros de negocios que visitan plantas como GM o BMW. Cuenta con acceso a Starbucks y restaurante The Hub del hotel contiguo.',
    amenities: [
      { key: 'buffet', value: 'Desayuno Buffet en cortesía' },
      { key: 'room-service', value: 'Room Service' },
      { key: 'gym', value: 'Gimnasio' },
      { key: 'alberca', value: 'Alberca ejecutiva techada y climatizada' },
      { key: 'wifi', value: 'Wifi' },
      { key: 'blackout', value: 'Habitaciones Black Out total' },
      { key: 'almohada', value: 'Menú de Almohadas' },
      { key: 'caja-seguridad', value: 'Caja de seguridad' },
      { key: 'lavanderia', value: 'Servicio de lavandería y tintorería' },
      { key: 'estacion-lavado', value: 'Estación de lavandería autoservicio' },
      { key: 'estacionamiento', value: 'Estacionamiento gratuito' },
      { key: 'estacion-carga', value: 'Centro de carga de automóviles eléctricos' },
      // { key: 'cafeteria', value: 'Sucursal Starbucks dentro del estacionamiento' },
      // { key: 'cafeteria', value: 'Cafetera y kit de café en habitación.' },
      // { key: 'llamadas', value: 'Llamadas telefónicas locales y nacionales a números fijos y móviles sin costo.' },
      // { key: 'musica', value: 'Música ambiental de género pop 90s y 2000s en inglés' }
    ]
  },
  {
    id: 'irapuato',
    sede: 'Irapuato',
    description: `Se encuentra ubicado accesando a la ciudad sobre carretera 45 proveniente de las ciudades de León, Guadalajara, Querétaro a tan solo 5 minutos de INFORUM Irapuato.<br/><br/>Hotel ubicado en Paseo de la Solidaridad esq. 4to cinturón Vial. Somos el hotel “a la entrada” de la ciudad de Irapuato, muy cercano a la autopista, por lo que somos opción para viajeros en tránsito, además de los de destino por cuestiones laborales/profesionales.<br/><br/>Ofrece una barra de buffet nocturno para cenas a $180 pesos por persona de 6:30pm a 10:00pm. Barra de ensalada, 2 guisos platillo fuerte, postre y bebidas.<br/><br/>Mini Store 24/7 en front desk. Venta de refrescos, botanas, dulces así como artículos de higiene personal y medicamento básico.`,
    url: 'https://www.wyndhamhotels.com/es-xl/microtel/irapuato-mexico/microtel-inn-and-suites-by-wyndham-irapuato/rooms-rates',
    whatsapp: '+5214622377775',
    street: 'Paseo de la Solidaridad esquina con 4to Cinturón Vial',
    neighborhood: 'Entrada de la ciudad',
    cp: '36500',
    city: 'Irapuato',
    state: 'Guanajuato',
    country: 'México',
    rate: 4.7,
    stars: '★★★★',
    ratings: 142,
    mapUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3733.720206097937!2d-101.3569403!3d20.720425!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x842b8001196b5ef3%3A0xe2fc23ebd66da2e7!2sMicrotel%20Inn%20%26%20Suites%20by%20Wyndham%20Irapuato!5e0!3m2!1ses!2smx!4v1748705400000!5m2!1ses!2smx',
    mapDescription: 'Hotel ideal para viajeros de negocios o tránsito. A sólo 5 minutos de INFORUM Irapuato, ubicado estratégicamente en la entrada de la ciudad con fácil acceso a la autopista.',
    amenities: [
      { key: 'buffet', value: 'Desayuno Buffet en cortesía' },
      { key: 'cafeteria', value: 'Cena Buffet a precio especial' },
      { key: 'vending', value: 'Mini Store 24/7 en front desk' },
      { key: 'gym', value: 'Gimnasio' },
      { key: 'alberca', value: 'Alberca ejecutiva techada y climatizada' },
      { key: 'wifi', value: 'Wifi' },
      { key: 'blackout', value: 'Habitaciones Black Out total' },
      { key: 'almohada', value: 'Menú de Almohadas' },
      { key: 'caja-seguridad', value: 'Caja de seguridad' },
      { key: 'lavanderia', value: 'Servicio de lavandería y tintorería' },
      { key: 'estacion-lavado', value: 'Estación de lavandería autoservicio' },
      { key: 'estacionamiento', value: 'Estacionamiento gratuito' },
      { key: 'estacion-carga', value: 'Centro de carga de automóviles eléctricos' },
      // { key: 'checkin', value: 'Check Inn Express con bebida de bienvenida' },
      // { key: 'cafeteria', value: 'Cafetera y kit de café en habitación.' },
      // { key: 'llamadas', value: 'Llamadas telefónicas locales y nacionales a números fijos y móviles sin costo.' },
      // { key: 'musica', value: 'Música ambiental de género pop 90s y 2000s en inglés' }
    ]
  },
  {
    id: 'gdl',
    sede: 'Guadalajara Sur',
    description: `Se encuentra en La Gourmeteria. Centro comercial dedicado a la recreación y gastronomía. Restaurantes, bar (Sala de despecho), cine, gimnasio.<br/><br/>Se encuentra en el sur de la ciudad de Guadalajara muy cercano a múltiples terrazas y salones de eventos, lo que nos permite otorgar hospedaje a personas tanto foráneas como locales para eventos en dichos salones y terrazas cercanos al hotel.<br/><br/>Cercano a lienzos Charros en Tlajomulco de Zuñiga donde se celebran encuentros charros anualmente.<br/><br/>Mini Store 24/7 en front desk. Venta de refrescos, botanas, dulces así como artículos de higiene personal y medicamento básico.<br/><br/>Vending Machine`,
    url: 'https://www.wyndhamhotels.com/es-xl/microtel/guadalajara-mexico/microtel-inn-and-suites-guadalajara-sur/rooms-rates',
    whatsapp: '+5213317678117',
    street: 'Av. López Mateos Sur 1710',
    neighborhood: 'La Gourmetería, Tlajomulco',
    cp: '45645',
    city: 'Guadalajara',
    state: 'Jalisco',
    country: 'México',
    rate: 4.8,
    stars: '★★★★',
    ratings: 189,
    mapUrl: 'https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d4868.205999076312!2d-103.4493752!3d20.5861316!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8428add1937a660d%3A0xebb65cb9ca16a54f!2sMicrotel%20Inn%20%26%20Suites%20by%20Wyndham%20Guadalajara%20Sur!5e1!3m2!1ses!2sus!4v1748973034556!5m2!1ses!2sus',
    mapDescription: 'Hotel cómodo ubicado dentro del centro comercial La Gourmetería, ideal para eventos sociales y acceso rápido a la zona sur de Guadalajara.',
    amenities: [
      { key: 'buffet', value: 'Desayuno Buffet en cortesía' },
      { key: 'vending', value: 'Mini Store 24/7 en front desk' },
      { key: 'gym', value: 'Gimnasio' },
      { key: 'alberca', value: 'Alberca ejecutiva techada y climatizada' },
      { key: 'wifi', value: 'Wifi' },
      { key: 'blackout', value: 'Habitaciones Black Out total' },
      { key: 'almohada', value: 'Menú de Almohadas' },
      { key: 'caja-seguridad', value: 'Caja de seguridad' },
      { key: 'lavanderia', value: 'Servicio de lavandería y tintorería' },
      { key: 'estacion-lavado', value: 'Estación de lavandería autoservicio' },
      { key: 'estacionamiento', value: 'Estacionamiento gratuito' },
      { key: 'estacion-carga', value: 'Centro de carga de automóviles eléctricos' },
      // { key: 'vending', value: 'Vending Machine' },
      // { key: 'cafeteria', value: 'Cafetera y kit de café en habitación.' },
      // { key: 'llamadas', value: 'Llamadas telefónicas locales y nacionales a números fijos y móviles sin costo.' },
      // { key: 'musica', value: 'Música ambiental de género pop 90s y 2000s en inglés' }
    ]
  }
];